### PR TITLE
Fix #31 - Update twitter status to change in karma

### LINKED ISSUE #31: Update twitter status to contain the amount of karma gained that day.
This requires parsing the karma log.

### PR DESCRIPTION
**Pull request by porglezomp**
* Move twitter status updating into the main loop
- Remove checking for an increase in karma before updating status
+ Add karma_yesterday() to parse karma.txt and determine the amount
  of karma gained during the previous day

* Moved reddit comment string into a variable called message_template
* Reformatted a few lines for line length
* Change already_done to a set instead of a list for performance

Requesting a code review and test

### CODE REVIEW

**Comment by powderblock** [comment]
I have been testing this.
I would like very verbose testing due the issues we've been facing lately. Everything so far looks good and is working.

Going to test this for at least two hours for the new karma stuff.

**Comment by powderblock** [comment]
So far, so good.  

Twitter desc is updating properly.

**Comment by porglezomp** [comment]
We should change the message to have "karma" after "{karma}"

**Comment by powderblock** [comment]
I think that's enough testing? Everything works great. Just add karma after {karma} when updating Twitter description.  

Ready to merge when you add that.

**Comment by porglezomp** [comment]
Okay, it's ready to be merged then.

**Pull request merged**
